version: '2.1'
services:
  config:
    build: config
    ports:
      - 8888:8888

  api-gateway:
    build: api-gateway
    ports:
      - 8080:8080
    depends_on:
      config:
        condition: service_healthy

  file-service:
    build: file-scan-service
    ports:
      - 8081:8081
    depends_on:
      config:
        condition: service_healthy
